<nav>
                <img src="../images/logo.png" alt="NeuroByte Logo" class="logo">
                <ul>
                    <li class="link"><a href="index.php">Home</a></li>
                    <li class="link"><a href="jobs.php">Jobs</a></li>
                    <li class="link"><a href="about.php">About</a></li>
                    <li class="link"><a href="login.php">Log In</a></li>
                        <a href="mailto:info@neurobyte.com.au">info@neurobyte.com.au</a>
                    </li>
                </ul>
</nav>